default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # host: localhost

development:
  <<: *default
  database: vonage_live
  # username: postgres
  password: password
  # host: localhost

test:
  <<: *default
  database: vonage_live_test
  # username: postgres
  password: 'postgres'

production:
  database: 'd9d1kvivd4rc1n'
  username: 'kulcxmvhsztdgn'
  port: 5432
  uri: 'postgres://kulcxmvhsztdgn:8349030149598b2b6941170ac9d28424b8e47b45506b0093f441f988cba33f3b@ec2-52-86-56-90.compute-1.amazonaws.com:5432/d9d1kvivd4rc1n'
  password: '8349030149598b2b6941170ac9d28424b8e47b45506b0093f441f988cba33f3b'
